[tool.black]
line-length = 100
target-version = ["py311"]
include = "ai-insight-suite|ai_insight_suite"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [
  ".venv",
  "__pycache__",
  ".git",
  "ai-insight-suite/services/**/examples/**",
]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict_optional = true
warn_unused_ignores = true
warn_return_any = true
exclude = [
  "ai-insight-suite/services/.*/examples/.*",
]


